[user]
name = "Daniel Lundin"
email = "dln@arity.se"

[ui]
default-command = "l"
diff-editor = ["scm-diff-editor", "--dir-diff", "$left", "$right"]
pager = ["delta", "--line-numbers", "--max-line-distance=0.9"]

[aliases]
l = ["log", "--ignore-working-copy", "-r", "(main..@): | (main..@)-"]
la = ["log", "--ignore-working-copy", "-r", "all()"]
b = ["branch", "list"]
n = ["new", "main"]
d = ["diff"]

[revset-aliases]
# The `main.. &` bit is an optimization to scan for non-`mine()` commits only
# among commits that are not in `main`.
"immutable_heads()" = "main@origin | (main@origin.. & ~mine())"

