[metadata]
  name = "Shelman Dark"
  origin_url = ""

[colors]
  ansi = ["#000000", "#ff0035", "#85ff00", "#ffc900", "#00a7ff", "#cb01ff", "#00e0ff", "#f0f0f0"]
  brights = ["#000000", "#ffb4af", "#d2ffba", "#ffebb7", "#b1deff", "#edb5ff", "#bdf4ff", "#ffffff"]
  background = "#1e2835"
  foreground = "#e0e0e0"
  cursor_bg = "#ffcc00"
  cursor_fg = "#000000"
  cursor_border = "#ffcc00"
  selection_bg = "#d7d7d7"
  selection_fg = "#000000"
