
# GENERAL ==============================

warning = { fg = "#ff7700", bg = "#221100", modifierd = [ "italic" ] }
error = { fg = "#ff0038", bg = "#220000", modifiers = [ "italic" ] }
hint = { fg = "#00d992", bg = "#002211", modifierd = [ "italic" ]  }
info = { fg = "#ffcc00", bg = "#222200", modifiers = ["italic"] }
diagnostic = { fg = "#c49848"}
"diagnostic.info" = { underline = { color = "#ffcc00", style = "curl" } }
"diagnostic.hint" = { fg = "#00d992", underline = { color = "#00d992", style = "curl" } }
"diagnostic.warning" = { fg = "#ff7700", underline = { color = "#ff7700", style = "curl" } }
"diagnostic.error" = { fg = "#ff0038", underline = { color = "#ff0038", style = "curl" } }
"diagnostic.unnecessary" = { fg = "#ffcc00", modifiers = ["dim", "italic"], underline = { style = "curl" } }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }


# UI ==============================
# For styling helix itself.

'ui.background' = { bg="background" }
'ui.background.separator' = { fg="#00a171" } 
'ui.window' = { bg="#224466" }
'ui.gutter' = { bg="#11171d" }

'ui.text' = { fg = "#cccccc" }
'ui.text.focus' = { bg = "#294467" }
'ui.text.info' = { }

'ui.cursor' = { bg = "#00a171", fg = "#000000" }
'ui.cursor.primary' = { bg ="#23fdb6", fg = "#000000" }
'ui.cursor.insert' = { fg = "#ff0000" }
'ui.cursor.select' = { fg = "#3399ff" }
'ui.cursor.match' = { fg = "#000000", bg = "#ffd54f" }
'ui.cursorline.primary' = { bg = "#141b23" }

'ui.selection' = { bg = "#294467" }
'ui.selection.primary' = { bg = "#294467" }

'ui.linenr' = { fg = "#374351", modifiers = [ "bold", "italic" ] }
'ui.linenr.selected' = { fg = "#617d9d", bg = "#14202e" }

'ui.virtual' = {  }
"ui.virtual.indent-guide" = { fg = "#273341" }
"ui.virtual.inlay-hint" = { fg = "#51a0cf", modifiers = ["italic", "bold"] }
'ui.virtual.ruler' = { bg = "#11171d" }
'ui.virtual.whitespace' = { }
'ui.virtual.wrap' = { fg = "#ffd54f" }
"ui.virtual.jump-label" = { fg = "#96ffe6", bg = "#051e33", modifiers = ["bold", "italic"] }

# 'ui.statusline' = { bg = "#151920", fg = "#4d5a6c" }
'ui.statusline' = { bg = "#11171d", fg = "#637184", modifiers = ["italic", "bold"] }
'ui.statusline.inactive' = { }
"ui.statusline.normal" = { }
"ui.statusline.insert" = { fg = "#d7b640" }
"ui.statusline.select" = { fg = "#3dc9ff" }

'ui.help' = { }

'ui.highlight' = { bg="#224466" }
"ui.highlight.frameline" = { }

'ui.menu' = { bg = "#242d38", fg="#bfd5e2" }
'ui.menu.selected' = { bg = "#135d7e" }

'ui.popup' = { bg = "#253d6b", fg="#b2c6e9" }
'ui.popup.info' = { }


# SYNTAX HIGHLIGHTING ==============================
# All the keys here are Treesitter scopes.

'property' = { }
'special' = { fg="#ffecd3" }
'attribute' = { }

'type' = { }
'type.builtin' = { }
'type.enum.variant' = { }

'constructor' = { }

'constant' = { }
'constant.builtin' = { }
'constant.builtin.boolean' = { }
'constant.character' = { }
'constant.character.escape' = { }
'constant.numeric'  = { }
'constant.numeric.integer' = { }
'constant.numeric.float' = { }

'string' = { fg="#88ab8a", modifiers=["italic"] }
'string.regexp' = { }
'string.special' = { }
'string.special.path' = { }
'string.special.url' = { }
'string.special.symbol' = { }

'comment' = { fg = "#e57373", modifiers = ["bold", "italic"] }
'comment.line' = { }
'comment.block' = { }
'comment.block.documentation' = { }

'variable' = { fg="#999999", modifiers = [ "italic" ] }
# 'variable.builtin' = { }
'variable.parameter' = { fg = "#eeccaa", modifiers = [ "italic" ] }
# 'variable.other.member' = { }

'label' = { }

'punctuation' = { fg = "#b0bec5" }
'punctuation.delimiter' = { fg = "#b0bec5" }
'punctuation.bracket' = { fg = "#b0bec5" }

'keyword' = { fg = "#d5d5d5" }
# 'keyword.control' = { }
# 'keyword.control.conditional' = { }
# 'keyword.control.repeat' = { }
# 'keyword.control.import' = { }
# 'keyword.control.return' = { }
# 'keyword.control.exception' = { }
# 'keyword.operator' = { }
# 'keyword.directive' = { }
# 'keyword.function' = { }

'operator' = { }

'function' = { fg = "#f7f7f7" }
'function.builtin' = { }
'function.method' = { }
'function.macro' = { }
'function.special' = { }

'tag' = { }
'tag.error' = { }

'namespace' = { fg = "#b0bec5" }


# Markup ==============================
# Colors for markup languages, like Markdown or XML.

'markup.heading.1' = { }
'markup.heading.2' = { }
'markup.heading.3' = { }
'markup.heading.4' = { }
'markup.heading.5' = { }
'markup.heading.6' = { }
'markup.heading.marker' = { }

'markup.list' = { }
'markup.list.numbered' = { }
'markup.list.unnumbered' = { }

'markup.bold' = { }
'markup.italic' = { }

'markup.link' = { }
'markup.link.url' = { }
'markup.link.label' = { }
'markup.link.text' = { }

'markup.quote' = { }


# Markup - Interface ==============================
# "These scopes are used for theming the editor interface."

'markup.normal' = { }
'markup.normal.completion' = { }
'markup.normal.raw' = { }

'markup.heading.completion' = { }
'markup.heading.raw' = { }

'markup.raw' = { }
'markup.raw.block' = { }
'markup.raw.inline' = { }
'markup.raw.inline.completion' = { }
'markup.raw.inline.hover' = { }

# Diff ==============================
# Version control changes.

'diff.plus' = { fg = "#678350" }
'diff.minus' = { fg = "#ff0038" }
'diff.delta' = { fg = "#897a21" }
'diff.delta.gutter' = { fg = "#ffff00" }
# 'diff.delta.moved' = { }


[palette] # Define your custom colors here.
white = '#ffffff'

