[metadata]
name = "Shelman Light"
origin_url = ""

[colors]
ansi = [
  "#000000",
  "#9e001d",
  "#306300",
  "#deae00",
  "#00669e",
  "#7d009e",
  "#008a9e",
  "#f7f7f7",
]

brights = [
  "#000000",
  "#ff0035",
  "#509e00",
  "#ffc900",
  "#00a7ff",
  "#cb01ff",
  "#00e0ff",
  "#ffffff",
]

background = "#fefeff"
# foreground = "#2c363c"
foreground = "#000000"
cursor_bg = "#aa0000"
cursor_fg = "#ffffff"
cursor_border = "#ffffff"
selection_bg = "#ffe6a4"
selection_fg = "#483600"
