[metadata]
name = "Shelman Dark"
origin_url = ""

[colors]
ansi = [
  "#000000",
  "#ff0035",
  "#85ff00",
  "#ffc900",
  "#00a7ff",
  "#cb01ff",
  "#00e0ff",
  "#f0f0f0",
]

brights = [
  "#000000",
  "#ff8c88",
  "#baff94",
  "#ffe090",
  "#88ccff",
  "#e38dff",
  "#97eeff",
  "#ffffff",
]

#background = "#000000"
background = "#0d1117"

# background = "#11171d"
#background = "#171e26"
# background = "#161923"
# foreground = "#e3e0cd"
# foreground = "#d3d0bd"
#foreground = "#cccccc"
foreground = "#b2b2b2"
cursor_bg = "#00d992"
cursor_fg = "#000000"
cursor_border = "#000000"
selection_bg = "#d7d7d7"
selection_fg = "#000000"
