theme = "sumi-e"

[editor]
true-color = true
undercurl = true
cursorline = true
color-modes = true
auto-pairs = false 
popup-border = "all"
rulers = [80]
gutters = ["diagnostics", "line-numbers", "spacer", "diff", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "│" # "╎"
render = true
skip-levels = 1

[editor.statusline]
separator = "│"
mode.normal = "  "
mode.insert = " "
mode.select = "󰒅 "
left = ["spinner", "mode", "diagnostics"]
center = ["file-name", "file-encoding"]
right = ["version-control", "separator", "selections", "register", "separator", "position"]

[editor.lsp]
display-inlay-hints = true
display-messages = true

[keys.normal]
backspace = "delete_char_backward"
C-h = "delete_char_backward"
C = ["select_mode", "goto_line_end", "normal_mode", "change_selection_noyank"]
H = ":toggle lsp.display-inlay-hints"
Z = { Z = ":write-quit-all" }
esc = ["keep_primary_selection", "collapse_selection"]
"`" = ["goto_last_accessed_file"]
tab = ["buffer_picker"]
C-r = ":config-reload"
C-f = [":new", ":insert-output lf -selection-path=/dev/stdout", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!", ":redraw"]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
x = "extend_line"

[keys.select]
x = "extend_line"
