[[language]]
name = "rust"
auto-format = true
roots = [
  "Cargo.toml",
  "Cargo.lock"
]
language-servers = [
    "rust-analyzer",
    "gpt",
]

[[language]]
name = "go"
language-servers = [
    "gopls",
    "gpt",
]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.inlayHints]
bindingModeHints.enable = false
chainingHints.enable = false
# closingBraceHints.enable = false
closingBraceHints.minLines = 10
closureReturnTypeHints.enable = "with_block"
# discriminantHints.enable = "fieldless"
discriminantHints.enable = "always"
lifetimeElisionHints.enable = "skip_trivial"
parameterHints.enable = true
typeHints.enable = true
typeHints.hideClosureInitialization = false

[language-server.gpt]
command = "helix-gpt"
args = ["--handler", "copilot", "--logFile", "/home/dln/.cache/helix/helix-gpt.log"]

